# Generated by Django 4.2.16 on 2024-10-16 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(max_length=512)),
                ('password', models.TextField(max_length=512)),
                ('role', models.TextField(max_length=100)),
            ],
        ),
    ]
