# Generated by Django 4.2.16 on 2024-10-16 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='username',
            field=models.TextField(max_length=512, unique=True),
        ),
    ]
