# Generated by Django 4.2.16 on 2024-11-09 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_users_line_user_id_usersprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersprofile',
            name='profile_picture_url',
        ),
        migrations.CreateModel(
            name='UsersFavoriteSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_from', models.IntegerField(default=0)),
                ('price_to', models.IntegerField(default=0)),
                ('space', models.DecimalField(decimal_places=2, max_digits=5)),
                ('room', models.IntegerField(default=0)),
                ('toilet', models.IntegerField(default=0)),
                ('floor_from', models.IntegerField(default=0)),
                ('floor_to', models.IntegerField(default=0)),
                ('location', models.CharField(max_length=1000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.users')),
            ],
        ),
    ]
