# Generated by Django 4.2.16 on 2024-11-09 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_remove_usersprofile_profile_picture_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersfavoritesearch',
            name='space',
        ),
        migrations.AddField(
            model_name='usersfavoritesearch',
            name='space_from',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='usersfavoritesearch',
            name='space_to',
            field=models.DecimalField(decimal_places=2, default=999, max_digits=5),
        ),
        migrations.AlterField(
            model_name='usersfavoritesearch',
            name='price_to',
            field=models.IntegerField(default=100000000),
        ),
    ]
