# Generated by Django 4.2.16 on 2024-11-09 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_remove_usersfavoritesearch_space_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersfavoritesearch',
            old_name='room',
            new_name='room_from',
        ),
        migrations.RenameField(
            model_name='usersfavoritesearch',
            old_name='toilet',
            new_name='toilet_from',
        ),
        migrations.AddField(
            model_name='usersfavoritesearch',
            name='room_to',
            field=models.IntegerField(default=99),
        ),
        migrations.AddField(
            model_name='usersfavoritesearch',
            name='toilet_to',
            field=models.IntegerField(default=99),
        ),
        migrations.AlterField(
            model_name='usersfavoritesearch',
            name='location',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
