# Generated by Django 4.2.16 on 2024-11-14 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_remove_usersprofile_id_alter_usersprofile_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersfavoritesearch',
            old_name='floor_from',
            new_name='floor_search_from',
        ),
        migrations.RenameField(
            model_name='usersfavoritesearch',
            old_name='floor_to',
            new_name='floor_search_to',
        ),
        migrations.RenameField(
            model_name='usersfavoritesearch',
            old_name='price_from',
            new_name='price_search_from',
        ),
        migrations.RenameField(
            model_name='usersfavoritesearch',
            old_name='price_to',
            new_name='price_search_to',
        ),
        migrations.RenameField(
            model_name='usersfavoritesearch',
            old_name='room_from',
            new_name='room_search_from',
        ),
        migrations.RenameField(
            model_name='usersfavoritesearch',
            old_name='room_to',
            new_name='room_search_to',
        ),
        migrations.RenameField(
            model_name='usersfavoritesearch',
            old_name='space_from',
            new_name='space_search_from',
        ),
        migrations.RenameField(
            model_name='usersfavoritesearch',
            old_name='space_to',
            new_name='space_search_to',
        ),
        migrations.RenameField(
            model_name='usersfavoritesearch',
            old_name='toilet_from',
            new_name='toilet_search_from',
        ),
        migrations.RenameField(
            model_name='usersfavoritesearch',
            old_name='toilet_to',
            new_name='toilet_search_to',
        ),
        migrations.AddField(
            model_name='usersfavoritesearch',
            name='desc_search',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
