# Generated by Django 4.2.16 on 2024-11-16 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_rename_floor_from_usersfavoritesearch_floor_search_from_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='tier',
            field=models.IntegerField(default=0),
        ),
    ]
