# Generated by Django 4.2.16 on 2025-02-15 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_usersfavoritesearch_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersfavoritesearch',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
