# Generated by Django 4.2.16 on 2025-03-23 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_alter_usersfavoritesearch_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersfavoritesearch',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='usersprofile',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
